# Generated by Django 4.2.8 on 2024-01-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_menuitems"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitems", old_name="course", new_name="category",
        ),
    ]
