# Generated by Django 4.2.8 on 2024-01-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_course_menuitems_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitems", old_name="name", new_name="itemname",
        ),
    ]
